# General settings
# ---------------------------------------------------------------------------------------

lang:     en
title:    Francesco Camaglia
logo:     /figures/foto_1.png

author:
  # Used by `jekyll-feed`:
  name:                 Francesco Camaglia
  email:                francesco.camaglia@phys.ens.fr
  social:
    github:               camacesco
    email:                francesco.camaglia@phys.ens.fr
    #linkedin:             francesco-camaglia-812567207

# Theme
# ---------------------------------------------------------------------------------------

remote_theme: hydecorp/hydejack@v9

# Customizaton
# ----------------------------------------------------------------------------------------
 
# Sidebar image and theme color of the site.
accent_image:          /figures/background_2.jpg
accent_color:          rgb(79,177,186)    


# Menu
# ----------------------------------------------------------------------------------------

menu:
  - title:             Publications
    url:               /menu/publications/
  - title:             CV
    url:               /menu/cv/

  
# Plugins
# ----------------------------------------------------------------------------------------

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
