# General settings
# ---------------------------------------------------------------------------------------

lang:     en
title:    Francesco Camaglia
logo:     /figures/foto_1.png

author:
  # Used by `jekyll-feed`:
  name:                 Francesco Camaglia
  email:                francesco.camaglia@phys.ens.fr
  social:
    github:               camacesco
    email:                francesco.camaglia@phys.ens.fr
    #linkedin:             francesco-camaglia-812567207

# Theme
# ---------------------------------------------------------------------------------------

remote_theme: hydecorp/hydejack@v9

# Customizaton
# ----------------------------------------------------------------------------------------
 
# Sidebar image and theme color of the site.
accent_image:          /figures/background_2.jpg
accent_color:          rgb(79,177,186)    


# Menu
# ----------------------------------------------------------------------------------------

menu:
  - title:             Publications
    url:               /menu/publications/
  - title:             CV
    url:               /menu/cv/

  
# Plugins
# ----------------------------------------------------------------------------------------

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jemoji
  
# Other Plugins
# ---------------------------------------------------------------------------------------

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed
